/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperationValidation } from './operationValidation';
import { Domain } from './domain';


export interface AppUpdateOutput { 
    id?: string;
    name?: string | null;
    identifier?: string | null;
    isActive?: boolean;
    softwareId?: string;
    isDefault?: boolean;
    domain?: Domain;
    operationValidation?: OperationValidation;
    readonly operationValidationDescription?: string | null;
}

