/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LogAction } from './logAction';
import { LogType } from './logType';


export interface AuditingLogOutput { 
    userName?: string | null;
    userId?: string;
    dateTime?: Date;
    details?: string | null;
    actionName?: string | null;
    action?: LogAction;
    type?: LogType;
    tenantId?: string;
}

