/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensedAppStatus } from './licensedAppStatus';
import { Domain } from './domain';


export interface BundledLicensedAppOutput { 
    id?: string;
    name?: string | null;
    softwareId?: string;
    softwareName?: string | null;
    bundleName?: string | null;
    status?: LicensedAppStatus;
    numberOfLicenses?: number;
    additionalNumberOfLicenses?: number;
    licensedBundleId?: string;
    domain?: Domain;
}

