/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Domain = 'Sales' | 'Purchases' | 'Billing' | 'Financial' | 'Rma' | 'Logistics' | 'Fiscal' | 'Accounting' | 'Engineering' | 'Production' | 'Maintenance' | 'QualityAssurance' | 'HumanResources' | 'Configurations' | 'Development' | 'Customized' | 'Licensing' | 'Reports' | 'Mobile' | 'Projects';

export const Domain = {
    Sales: 'Sales' as Domain,
    Purchases: 'Purchases' as Domain,
    Billing: 'Billing' as Domain,
    Financial: 'Financial' as Domain,
    Rma: 'Rma' as Domain,
    Logistics: 'Logistics' as Domain,
    Fiscal: 'Fiscal' as Domain,
    Accounting: 'Accounting' as Domain,
    Engineering: 'Engineering' as Domain,
    Production: 'Production' as Domain,
    Maintenance: 'Maintenance' as Domain,
    QualityAssurance: 'QualityAssurance' as Domain,
    HumanResources: 'HumanResources' as Domain,
    Configurations: 'Configurations' as Domain,
    Development: 'Development' as Domain,
    Customized: 'Customized' as Domain,
    Licensing: 'Licensing' as Domain,
    Reports: 'Reports' as Domain,
    Mobile: 'Mobile' as Domain,
    Projects: 'Projects' as Domain
};

