/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InsertBatchOperationsInput { 
    ids?: Array<string> | null;
    unselectedList?: Array<string> | null;
    allSelected?: boolean;
    advancedFilter?: string | null;
}

