/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseConsumeType } from './licenseConsumeType';
import { OperationValidation } from './operationValidation';
import { LicensingStatus } from './licensingStatus';


export interface LicenseTenantCreateOutput { 
    id?: string;
    accountId?: string;
    accountName?: string | null;
    status?: LicensingStatus;
    identifier?: string;
    expirationDateTime?: Date | null;
    licensedCnpjs?: string | null;
    administratorEmail?: string | null;
    licenseConsumeType?: LicenseConsumeType;
    readonly licenseConsumeDescription?: string | null;
    operationValidation?: OperationValidation;
    readonly operationValidationDescription?: string | null;
    notes?: string | null;
}

