/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensingStatus } from './licensingStatus';


export interface LicensedTenantViewOutput { 
    status?: LicensingStatus;
    identifier?: string;
    licensedTenantId?: string;
    expirationDateTime?: Date | null;
    licensedCnpjs?: string | null;
    administratorEmail?: string | null;
    accountId?: string;
    accountCompanyName?: string | null;
}

