/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseConsumeType } from './licenseConsumeType';
import { LicensingStatus } from './licensingStatus';


export interface LicenseTenantUpdateInput { 
    id: string;
    accountId: string;
    status: LicensingStatus;
    identifier: string;
    expirationDateTime?: Date | null;
    licenseConsumeType?: LicenseConsumeType;
    licensedCnpjs: string;
    administratorEmail: string;
    notes?: string | null;
}

