/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensedAppStatus } from './licensedAppStatus';
import { OperationValidation } from './operationValidation';


export interface LicensedAppUpdateOutput { 
    licensedTenantId?: string;
    licensedBundleId?: string | null;
    appId?: string;
    status?: LicensedAppStatus;
    numberOfLicenses?: number;
    additionalNumberOfLicenses?: number;
    numberOfTemporaryLicenses?: number;
    expirationDateOfTemporaryLicenses?: Date | null;
    expirationDateTime?: Date | null;
    operationValidation?: OperationValidation;
    readonly operationValidationDescription?: string | null;
}

