/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensedBundleStatus } from './licensedBundleStatus';


export interface LicensedBundleDetails { 
    bundleId?: string;
    identifier?: string | null;
    name?: string | null;
    status?: LicensedBundleStatus;
    numberOfLicenses?: number;
}

