/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OperationValidation = 'NoError' | 'DuplicatedEntry' | 'DuplicatedIdentifier' | 'UsedByOtherRegister' | 'AppAlreadyLicensed' | 'LicenseDoesNotExist' | 'CantRemoveFromLicenseDefaultApp' | 'NoLicensedAppWithSuchId' | 'CnpjAlreadyRegistered' | 'AccountIdAlreadyInUse' | 'InvalidNumberOfLicenses' | 'AdministrationEmailAlreadyInUse' | 'NoTenantWithSuchId' | 'InvalidGateway' | 'InfrastructureConfigurationAlreadyExists' | 'InvalidDate';

export const OperationValidation = {
    NoError: 'NoError' as OperationValidation,
    DuplicatedEntry: 'DuplicatedEntry' as OperationValidation,
    DuplicatedIdentifier: 'DuplicatedIdentifier' as OperationValidation,
    UsedByOtherRegister: 'UsedByOtherRegister' as OperationValidation,
    AppAlreadyLicensed: 'AppAlreadyLicensed' as OperationValidation,
    LicenseDoesNotExist: 'LicenseDoesNotExist' as OperationValidation,
    CantRemoveFromLicenseDefaultApp: 'CantRemoveFromLicenseDefaultApp' as OperationValidation,
    NoLicensedAppWithSuchId: 'NoLicensedAppWithSuchId' as OperationValidation,
    CnpjAlreadyRegistered: 'CnpjAlreadyRegistered' as OperationValidation,
    AccountIdAlreadyInUse: 'AccountIdAlreadyInUse' as OperationValidation,
    InvalidNumberOfLicenses: 'InvalidNumberOfLicenses' as OperationValidation,
    AdministrationEmailAlreadyInUse: 'AdministrationEmailAlreadyInUse' as OperationValidation,
    NoTenantWithSuchId: 'NoTenantWithSuchId' as OperationValidation,
    InvalidGateway: 'InvalidGateway' as OperationValidation,
    InfrastructureConfigurationAlreadyExists: 'InfrastructureConfigurationAlreadyExists' as OperationValidation,
    InvalidDate: 'InvalidDate' as OperationValidation
};

