export * from './accountServiceProxy';
import { AccountServiceProxy } from './accountServiceProxy';
export * from './appServiceProxy';
import { AppServiceProxy } from './appServiceProxy';
export * from './appQuotaServiceProxy';
import { AppQuotaServiceProxy } from './appQuotaServiceProxy';
export * from './auditingLogServiceProxy';
import { AuditingLogServiceProxy } from './auditingLogServiceProxy';
export * from './authorizationServiceProxy';
import { AuthorizationServiceProxy } from './authorizationServiceProxy';
export * from './bundleServiceProxy';
import { BundleServiceProxy } from './bundleServiceProxy';
export * from './cnpjServiceProxy';
import { CnpjServiceProxy } from './cnpjServiceProxy';
export * from './domainServiceProxy';
import { DomainServiceProxy } from './domainServiceProxy';
export * from './hostTenantServiceProxy';
import { HostTenantServiceProxy } from './hostTenantServiceProxy';
export * from './infrastructureConfigurationServiceProxy';
import { InfrastructureConfigurationServiceProxy } from './infrastructureConfigurationServiceProxy';
export * from './licenseServerServiceProxy';
import { LicenseServerServiceProxy } from './licenseServerServiceProxy';
export * from './licensedTenantBatchOperationsServiceProxy';
import { LicensedTenantBatchOperationsServiceProxy } from './licensedTenantBatchOperationsServiceProxy';
export * from './licensedTenantViewServiceProxy';
import { LicensedTenantViewServiceProxy } from './licensedTenantViewServiceProxy';
export * from './licensingServiceProxy';
import { LicensingServiceProxy } from './licensingServiceProxy';
export * from './licensingManagementStatisticsServiceProxy';
import { LicensingManagementStatisticsServiceProxy } from './licensingManagementStatisticsServiceProxy';
export * from './licensingOrganizationServiceProxy';
import { LicensingOrganizationServiceProxy } from './licensingOrganizationServiceProxy';
export * from './softwareServiceProxy';
import { SoftwareServiceProxy } from './softwareServiceProxy';
export * from './tenantInfoServiceProxy';
import { TenantInfoServiceProxy } from './tenantInfoServiceProxy';
export * from './tenantQuotaServiceProxy';
import { TenantQuotaServiceProxy } from './tenantQuotaServiceProxy';
export * from './zipCodeServiceProxy';
import { ZipCodeServiceProxy } from './zipCodeServiceProxy';
export const APIS = [AccountServiceProxy, AppServiceProxy, AppQuotaServiceProxy, AuditingLogServiceProxy, AuthorizationServiceProxy, BundleServiceProxy, CnpjServiceProxy, DomainServiceProxy, HostTenantServiceProxy, InfrastructureConfigurationServiceProxy, LicenseServerServiceProxy, LicensedTenantBatchOperationsServiceProxy, LicensedTenantViewServiceProxy, LicensingServiceProxy, LicensingManagementStatisticsServiceProxy, LicensingOrganizationServiceProxy, SoftwareServiceProxy, TenantInfoServiceProxy, TenantQuotaServiceProxy, ZipCodeServiceProxy];
