// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viasoft.Licensing.CustomerLicensing.Infrastructure.EntityFrameworkCore;

namespace Viasoft.Licensing.CustomerLicensing.Infrastructure.Migrations
{
    [DbContext(typeof(ViasoftCustomerLicensingDbContext))]
    [Migration("20191114145042_Adding LicenseUsageInRealTime Entity")]
    partial class AddingLicenseUsageInRealTimeEntity
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Viasoft.Licensing.CustomerLicensing.Domain.Entities.LicenseUsageInRealTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("AdditionalLicense");

                    b.Property<int>("AdditionalLicenses");

                    b.Property<int>("AdditionalLicensesConsumed");

                    b.Property<string>("AppIdentifier")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<int>("AppLicenses");

                    b.Property<int>("AppLicensesConsumed");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<int>("AppStatus");

                    b.Property<string>("BundleIdentifier")
                        .HasMaxLength(450);

                    b.Property<string>("BundleName")
                        .HasMaxLength(450);

                    b.Property<string>("Cnpj")
                        .HasMaxLength(450);

                    b.Property<DateTime>("LastUpdate");

                    b.Property<int>("LicensingStatus");

                    b.Property<string>("SoftwareIdentifier")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(450);

                    b.Property<DateTime>("StartTime");

                    b.Property<Guid>("TenantId");

                    b.Property<string>("User")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("LicenseUsageInRealTime");
                });
#pragma warning restore 612, 618
        }
    }
}
