// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viasoft.Licensing.CustomerLicensing.Infrastructure.EntityFrameworkCore;

namespace Viasoft.Licensing.CustomerLicensing.Infrastructure.Migrations
{
    [DbContext(typeof(ViasoftCustomerLicensingDbContext))]
    [Migration("20210915135605_Fixed LicensingModels Column name")]
    partial class FixedLicensingModelsColumnname
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Viasoft.Licensing.CustomerLicensing.Domain.Entities.LicenseUsageInRealTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("AdditionalLicense")
                        .HasColumnType("bit");

                    b.Property<int>("AdditionalLicenses")
                        .HasColumnType("int");

                    b.Property<int>("AdditionalLicensesConsumed")
                        .HasColumnType("int");

                    b.Property<string>("AppIdentifier")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AppLicenses")
                        .HasColumnType("int");

                    b.Property<int>("AppLicensesConsumed")
                        .HasColumnType("int");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AppStatus")
                        .HasColumnType("int");

                    b.Property<string>("BrowserInfo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BundleIdentifier")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BundleName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DatabaseName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Domain")
                        .HasColumnType("int");

                    b.Property<string>("HostName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("HostUser")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Language")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("LicensingIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("LicensingStatus")
                        .HasColumnType("int");

                    b.Property<string>("LocalIpAddress")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OsInfo")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareIdentifier")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SoftwareVersion")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("User")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("licensingMode")
                        .HasColumnType("int");

                    b.Property<int>("licensingModel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LicensingIdentifier");

                    b.HasIndex("LicensingIdentifier", "User");

                    b.ToTable("LicenseUsageInRealTime");
                });

            modelBuilder.Entity("Viasoft.Licensing.CustomerLicensing.Domain.Entities.OwnedAppCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<Guid>("LicensingIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("OwnedAppCount");
                });
#pragma warning restore 612, 618
        }
    }
}
