// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Viasoft.Licensing.LicensingManagement.Infrastructure.EntityFrameworkCore;

namespace Viasoft.Licensing.LicensingManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ViasoftLicenseServerDbContext))]
    [Migration("20191106172450_Adding LicensedTenants_Property_Administrator_Email")]
    partial class AddingLicensedTenants_Property_Administrator_Email
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.App", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Identifier")
                        .HasMaxLength(450);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.Property<string>("Name")
                        .HasMaxLength(450);

                    b.Property<Guid>("SoftwareId");

                    b.HasKey("Id");

                    b.ToTable("App");
                });

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.Bundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Identifier")
                        .HasMaxLength(450);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsCustom");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.Property<string>("Name")
                        .HasMaxLength(450);

                    b.Property<Guid>("SoftwareId");

                    b.HasKey("Id");

                    b.ToTable("Bundle");
                });

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.BundledApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AppId");

                    b.Property<Guid>("BundleId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.HasKey("Id");

                    b.ToTable("BundledApp");
                });

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.LicensedApp", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AdditionalNumberOfLicenses");

                    b.Property<Guid>("AppId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.Property<Guid?>("LicensedBundleId");

                    b.Property<Guid>("LicensedTenantId");

                    b.Property<int>("NumberOfLicenses");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("LicensedApp");
                });

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.LicensedBundle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("BundleId");

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.Property<Guid>("LicensedTenantId");

                    b.Property<int>("NumberOfLicenses");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("LicensedBundle");
                });

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.LicensedTenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AdministratorEmail")
                        .HasMaxLength(450);

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<string>("CustomerCode")
                        .HasMaxLength(450);

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<DateTime?>("ExpirationDateTime");

                    b.Property<Guid>("Identifier");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.Property<string>("LicensedCnpjs")
                        .HasMaxLength(450);

                    b.Property<int>("NumberOfDaysToExpiration");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("LicensedTenant");
                });

            modelBuilder.Entity("Viasoft.Licensing.LicensingManagement.Domain.Entities.Software", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Company")
                        .HasMaxLength(450);

                    b.Property<DateTime>("CreationTime");

                    b.Property<Guid?>("CreatorId");

                    b.Property<Guid?>("DeleterId");

                    b.Property<DateTime?>("DeletionTime");

                    b.Property<string>("Identifier")
                        .HasMaxLength(450);

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsDeleted");

                    b.Property<DateTime?>("LastModificationTime");

                    b.Property<Guid?>("LastModifierId");

                    b.Property<string>("Name")
                        .HasMaxLength(450);

                    b.HasKey("Id");

                    b.ToTable("Software");
                });
#pragma warning restore 612, 618
        }
    }
}
