/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountStatus } from './accountStatus';
import { OperationValidation } from './operationValidation';


export interface AccountUpdateOutput { 
    id?: string;
    phone?: string | null;
    webSite?: string | null;
    email?: string | null;
    billingEmail?: string | null;
    tradingName?: string | null;
    companyName?: string | null;
    cnpjCpf?: string | null;
    status?: AccountStatus;
    street?: string | null;
    number?: string | null;
    detail?: string | null;
    neighborhood?: string | null;
    city?: string | null;
    state?: string | null;
    country?: string | null;
    zipCode?: string | null;
    operationValidation?: OperationValidation;
    readonly operationValidationDescription?: string | null;
}

