/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OperationValidation } from './operationValidation';


export interface GetCompanyByCnpjOutput { 
    id?: string;
    phone?: string | null;
    email?: string | null;
    neighborhood?: string | null;
    efr?: string | null;
    uf?: string | null;
    street?: string | null;
    city?: string | null;
    cnpj?: string | null;
    name?: string | null;
    number?: string | null;
    complement?: string | null;
    cep?: string | null;
    tradingName?: string | null;
    status?: string | null;
    operationValidation?: OperationValidation;
    readonly operationValidationDescription?: string | null;
}

