/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicenseConsumeType } from './licenseConsumeType';
import { LicensedTenantDetails } from './licensedTenantDetails';
import { LicensingStatus } from './licensingStatus';


export interface LicenseByIdentifier { 
    identifier?: string;
    licenseConsumeType?: LicenseConsumeType;
    status?: LicensingStatus;
    expirationDateTime?: Date | null;
    cnpjs?: Array<string> | null;
    licensedTenantDetails?: LicensedTenantDetails | null;
}

