/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LogAction = 'InsertAppInLicenses' | 'RemoveAppInLicenses' | 'InsertMultipleBundlesInMultipleLicenses' | 'InsertMultipleAppsInMultipleLicenses' | 'InsertMultipleAppsInMultipleBundles' | 'InsertMultipleAppsFromBundlesInLicenses';

export const LogAction = {
    InsertAppInLicenses: 'InsertAppInLicenses' as LogAction,
    RemoveAppInLicenses: 'RemoveAppInLicenses' as LogAction,
    InsertMultipleBundlesInMultipleLicenses: 'InsertMultipleBundlesInMultipleLicenses' as LogAction,
    InsertMultipleAppsInMultipleLicenses: 'InsertMultipleAppsInMultipleLicenses' as LogAction,
    InsertMultipleAppsInMultipleBundles: 'InsertMultipleAppsInMultipleBundles' as LogAction,
    InsertMultipleAppsFromBundlesInLicenses: 'InsertMultipleAppsFromBundlesInLicenses' as LogAction
};

