/**
 * Viasoft.Licensing.CustomerLicensing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent, HttpParameterCodec }       from '@angular/common/http';
import { CustomHttpParameterCodec }                          from '../encoder';
import { Observable }                                        from 'rxjs';

import { LicenseUserBehaviourHistoricOutputPagedResultDto } from '../model/licenseUserBehaviourHistoricOutputPagedResultDto';
import { LicenseUserBehaviourOutputPagedResultDto } from '../model/licenseUserBehaviourOutputPagedResultDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import { VsGridGetInput } from '@viasoft/components';
import { licenseUserBehaviourNamedOnlineOutputPagedResultDto } from '../model/licenseUserBehaviourNamedOnlineOutputPagedResultDto';
import { licenseUserBehaviourNamedOfflineOutputPagedResultDto } from '../model/licenseUserBehaviourNamedOfflineOutputPagedResultDto';
import { ProductType } from 'src/app/common/enums/ProductType';



@Injectable()
export class LicenseUserBehaviourServiceProxy {

    protected basePath = 'http://localhost';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();
    public encoder: HttpParameterCodec;

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (configuration) {
            this.configuration = configuration;
        }
        if (typeof this.configuration.basePath !== 'string') {
            if (typeof basePath !== 'string') {
                basePath = this.basePath;
            }
            this.configuration.basePath = basePath;
        }
        this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
    }

    /**
     * @param tzDatabaseName 
     * @param licensingIdentifier 
     * @param filter 
     * @param advancedFilter 
     * @param sorting 
     * @param skipCount 
     * @param maxResultCount 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getUsersBehaviour(tzDatabaseName?: string, licensingIdentifier?: string, filter?: string, advancedFilter?: string, sorting?: string, skipCount?: number, maxResultCount?: number, observe?: 'body', reportProgress?: boolean): Observable<LicenseUserBehaviourOutputPagedResultDto>;
    public getUsersBehaviour(tzDatabaseName?: string, licensingIdentifier?: string, filter?: string, advancedFilter?: string, sorting?: string, skipCount?: number, maxResultCount?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<LicenseUserBehaviourOutputPagedResultDto>>;
    public getUsersBehaviour(tzDatabaseName?: string, licensingIdentifier?: string, filter?: string, advancedFilter?: string, sorting?: string, skipCount?: number, maxResultCount?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<LicenseUserBehaviourOutputPagedResultDto>>;
    public getUsersBehaviour(tzDatabaseName?: string, licensingIdentifier?: string, filter?: string, advancedFilter?: string, sorting?: string, skipCount?: number, maxResultCount?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let queryParameters = new HttpParams({encoder: this.encoder});
        if (tzDatabaseName !== undefined && tzDatabaseName !== null) {
            queryParameters = queryParameters.set('TzDatabaseName', <any>tzDatabaseName);
        }
        if (licensingIdentifier !== undefined && licensingIdentifier !== null) {
            queryParameters = queryParameters.set('LicensingIdentifier', <any>licensingIdentifier);
        }
        if (filter !== undefined && filter !== null) {
            queryParameters = queryParameters.set('Filter', <any>filter);
        }
        if (advancedFilter !== undefined && advancedFilter !== null) {
            queryParameters = queryParameters.set('AdvancedFilter', <any>advancedFilter);
        }
        if (sorting !== undefined && sorting !== null) {
            queryParameters = queryParameters.set('Sorting', <any>sorting);
        }
        if (skipCount !== undefined && skipCount !== null) {
            queryParameters = queryParameters.set('SkipCount', <any>skipCount);
        }
        if (maxResultCount !== undefined && maxResultCount !== null) {
            queryParameters = queryParameters.set('MaxResultCount', <any>maxResultCount);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        const httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }


        return this.httpClient.get<LicenseUserBehaviourOutputPagedResultDto>(`${this.configuration.basePath}/Licensing/CustomerLicensing/LicenseUserBehaviour/GetUsersBehaviour`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    public getUserBehaviourFloating(input: VsGridGetInput, licensingIdentifier: string, bundleIdentifier: string, productType: ProductType): Observable<LicenseUserBehaviourOutputPagedResultDto> {
        let params = new HttpParams();
        if (licensingIdentifier) {
          params = params.set('LicensingIdentifier', licensingIdentifier);
        }
        if (productType) {
          params = params.set('ProductType', productType);
        }
        if (input.filter) {
          params = params.set('Filter', input.filter);
        }
        if (input.advancedFilter) {
          params = params.set('AdvancedFilter', input.advancedFilter);
        }
        if (input.sorting) {
          params = params.set('Sorting', input.sorting);
        }
        if (input.skipCount) {
          params = params.set('SkipCount', input.skipCount.toString());
        }
        if (input.maxResultCount) {
          params = params.set('MaxResultCount', input.maxResultCount.toString());
        }
        return this.httpClient.get<LicenseUserBehaviourOutputPagedResultDto>(`${this.configuration.basePath}/licensing/customer-licensing/user-behaviour/products/${bundleIdentifier}/floating`,
          {params});
    }

    public getUserBehaviourFromBundleNamedOnline(input: VsGridGetInput, licensedTenant: string, licensingIdentifier: string, bundleIdentifier: string, productId: string, productType: ProductType): Observable<licenseUserBehaviourNamedOnlineOutputPagedResultDto> {
        let params = new HttpParams();

        if (licensedTenant) {
          params = params.set('LicensedTenantId', licensedTenant);
        }
        if (licensingIdentifier) {
            params = params.set('LicensingIdentifier', licensingIdentifier);
        }
        if (productId) {
            params = params.set('ProductId', productId);
        }
        if (productType) {
          params = params.set('ProductType', productType);
        }
        if (input.filter) {
          params = params.set('Filter', input.filter);
        }
        if (input.advancedFilter) {
          params = params.set('AdvancedFilter', input.advancedFilter);
        }
        if (input.sorting) {
          params = params.set('Sorting', input.sorting);
        }
        if (input.skipCount) {
          params = params.set('SkipCount', input.skipCount.toString());
        }
        if (input.maxResultCount) {
          params = params.set('MaxResultCount', input.maxResultCount.toString());
        }
        return this.httpClient.get<licenseUserBehaviourNamedOnlineOutputPagedResultDto>(`${this.configuration.basePath}/licensing/customer-licensing/user-behaviour/products/${bundleIdentifier}/named/online`,
          {params});
    }

    public getUserBehaviourFromBundleNamedOffline(input: VsGridGetInput, licensedTenant: string, licensingIdentifier: string, bundleIdentifier: string, productId: string, productType: ProductType): Observable<licenseUserBehaviourNamedOfflineOutputPagedResultDto> {
      let params = new HttpParams();

      if (licensedTenant) {
        params = params.set('LicensedTenantId', licensedTenant);
      }
      if (licensingIdentifier) {
          params = params.set('LicensingIdentifier', licensingIdentifier);
      }
        if (productId) {
          params = params.set('ProductId', productId);
      }
      if (productType) {
        params = params.set('ProductType', productType);
      }
      if (input.filter) {
        params = params.set('Filter', input.filter);
      }
      if (input.advancedFilter) {
        params = params.set('AdvancedFilter', input.advancedFilter);
      }
      if (input.sorting) {
        params = params.set('Sorting', input.sorting);
      }
      if (input.skipCount) {
        params = params.set('SkipCount', input.skipCount.toString());
      }
      if (input.maxResultCount) {
        params = params.set('MaxResultCount', input.maxResultCount.toString());
      }
      return this.httpClient.get<licenseUserBehaviourNamedOfflineOutputPagedResultDto>(`${this.configuration.basePath}/licensing/customer-licensing/user-behaviour/products/${bundleIdentifier}/named/offline`,
        {params});
  }

}
