/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type CreateEnvironmentOutputStatus = 'NameConflict' | 'OrganizationUnitNotFound' | 'InProductionConflict' | 'NotTypedEnvironment' | 'InvalidDatabaseName' | 'Ok' | 'IdConflict';

export const CreateEnvironmentOutputStatus = {
    NameConflict: 'NameConflict' as CreateEnvironmentOutputStatus,
    OrganizationUnitNotFound: 'OrganizationUnitNotFound' as CreateEnvironmentOutputStatus,
    InProductionConflict: 'InProductionConflict' as CreateEnvironmentOutputStatus,
    NotTypedEnvironment: 'NotTypedEnvironment' as CreateEnvironmentOutputStatus,
    InvalidDatabaseName: 'InvalidDatabaseName' as CreateEnvironmentOutputStatus,
    Ok: 'Ok' as CreateEnvironmentOutputStatus,
    IdConflict: 'IdConflict'  as CreateEnvironmentOutputStatus
};

