/**
 * Viasoft.Licensing.CustomerLicensing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LicensedAppStatus } from './licensedAppStatus';
import { LicenseUsageAdditionalInformation } from './licenseUsageAdditionalInformation';
import { LicensingStatus } from './licensingStatus';


export interface LicenseUsageInRealTimeDetails { 
    tenantId: string;
    appIdentifier: string;
    appName: string;
    bundleIdentifier?: string | null;
    bundleName?: string | null;
    softwareName: string;
    softwareIdentifier: string;
    appLicenses?: number;
    appLicensesConsumed?: number;
    additionalLicenses?: number;
    additionalLicensesConsumed?: number;
    additionalLicense?: boolean;
    startTime: Date;
    user: string;
    cnpj: string;
    licensingStatus?: LicensingStatus;
    appStatus?: LicensedAppStatus;
    licenseUsageAdditionalInformation?: LicenseUsageAdditionalInformation | null;
}

