/**
 * Viasoft.Licensing.CustomerLicensing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LicenseUserBehaviourHistoricOutput { 
    tenantId?: string;
    cnpj?: string | null;
    user?: string | null;
    appIdentifier?: string | null;
    appName?: string | null;
    bundleIdentifier?: string | null;
    bundleName?: string | null;
    softwareName?: string | null;
    softwareIdentifier?: string | null;
    additionalLicense?: boolean;
    startTime?: Date;
    endTime?: Date;
    durationInMinutes?: number;
}

