/**
 * Viasoft.Licensing.CustomerLicensing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LicensingStatus = 'NeedsApproval' | 'Blocked' | 'Trial' | 'Active';

export const LicensingStatus = {
    NeedsApproval: 'NeedsApproval' as LicensingStatus,
    Blocked: 'Blocked' as LicensingStatus,
    Trial: 'Trial' as LicensingStatus,
    Active: 'Active' as LicensingStatus
};

