/**
 * Viasoft.Licensing.CustomerLicensing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LicenseUsageAdditionalInformation { 
    softwareVersion?: string | null;
    hostName?: string | null;
    hostUser?: string | null;
    localIpAddress?: string | null;
    language?: string | null;
    osInfo?: string | null;
    browserInfo?: string | null;
    databaseName?: string | null;
}

