/**
 * Viasoft.Licensing.CustomerLicensing
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OperationValidation = 'NoError' | 'NoTenantWithSuchId' | 'NoLicensedBundleWithSuchId' | 'TooManyNamedUserBundleLicenses' | 'NamedUserEmailAlreadyInUse' | 'NotANamedLicense' | 'NoNamedUser' | 'NoLicensedTenant' | 'NoLicensedBundle';

export const OperationValidation = {
    NoError: 'NoError' as OperationValidation,
    NoTenantWithSuchId: 'NoTenantWithSuchId' as OperationValidation,
    NoLicensedBundleWithSuchId: 'NoLicensedBundleWithSuchId' as OperationValidation,
    TooManyNamedUserBundleLicenses: 'TooManyNamedUserBundleLicenses' as OperationValidation,
    NamedUserEmailAlreadyInUse: 'NamedUserEmailAlreadyInUse' as OperationValidation,
    NotANamedLicense: 'NotANamedLicense' as OperationValidation,
    NoNamedUser: 'NoNamedUser' as OperationValidation,
    NoLicensedTenant: 'NoLicensedTenant' as OperationValidation,
    NoLicensedBundle: 'NoLicensedBundle' as OperationValidation
};

