/**
 * Viasoft.Sales.CommercialProposal.Core
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PermissoesNome = 'SettingsRead' | 'SettingsUpdate' | 'Environments.Read' | 'Environments.Update';

export const PermissoesNome = {
  SettingsRead: "Settings.Read" as PermissoesNome,
  SettingsUpdate: "Settings.Update" as PermissoesNome,
  EnvironmentsRead: "Environments.Read" as PermissoesNome,
  EnvironmentsUpdate: "Environments.Update" as PermissoesNome
};

