/**
 * Viasoft.Licensing.LicensingManagement
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type UpdateEnvironmentOutputStatus = 'NameConflict' | 'NotFound' | 'InProductionConflict' | 'NotTypedEnvironment' | 'InvalidDatabaseName' | 'Ok';

export const UpdateEnvironmentOutputStatus = {
    NameConflict: 'NameConflict' as UpdateEnvironmentOutputStatus,
    NotFound: 'NotFound' as UpdateEnvironmentOutputStatus,
    InProductionConflict: 'InProductionConflict' as UpdateEnvironmentOutputStatus,
    NotTypedEnvironment: 'NotTypedEnvironment' as UpdateEnvironmentOutputStatus,
    InvalidDatabaseName: 'InvalidDatabaseName' as UpdateEnvironmentOutputStatus,
    Ok: 'Ok' as UpdateEnvironmentOutputStatus
};

